web/router.ex
defmodule College.Router do
  use College.Web, :router

  require Ueberauth
  alias College.UserSession
  alias College.UserAuthentication
  
  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug UserSession
    plug College.LocalePlug
  end

  pipeline :user_authentication do
    plug UserAuthentication
  end
  
  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/api", College do
    pipe_through :api
    resources "/user_search", UserSearchController
  end

  scope "/auth", College do
    pipe_through :browser
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
    delete "/logout", AuthController, :delete
  end

  scope "/", College do
    pipe_through :browser # Use the default browser stack
    get "/", PageController, :index
    get "/artefacts", PageController, :artefacts
    get "/show_artefact", PageController, :show_artefact
    get "/admin", PageController, :admin_index
  end

  scope "/admin", College do
    pipe_through [:user_authentication,:browser  ] # Use the default browser stack
    resources "/artefacts", ArtefactController
    resources "/courses", CourseController
    resources "/credentials", CredentialsController
    resources "/exhibitions", ExhibitionController
    resources "/exhibitions_users", ExhibitionUserController
    resources "/user_courses", UserCourseController
    resources "/users", UserController
    get "/users/:id/show_edit_password",     UserController, :show_edit_password
    put "/users/:id/save_edit_password",     UserController, :save_edit_password
  end

end

web/views/layout_view.ex
defmodule College.LayoutView do
  use College.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello College!</title>
    <link rel="stylesheet" href='<%= static_path(@conn, "/css/app.css") %>'>
</head>

<body>
<div class="container">
    <header class="header">
        <nav role="navigation" class="navbar navbar-default">
            <div class="btn-group"">
                <a href="<%= page_path @conn, :index %>" class="btn btn-default">Home</a>

               </div>
                <div class="btn-group" id="dropdown1">
                <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1"
                        data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="true">
                    Admin menu
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                    <li><a href="<%= artefact_path @conn, :index %>">Artefacts</a></li>
                    <li><a href="<%= course_path @conn, :index %>">Courses</a></li>
                    <li><a href="<%= credentials_path @conn, :index %>">Credentials</a></li>
                    <li><a href="<%= exhibition_path @conn, :index %>">Exhibitions</a></li>
                    <li><a href="<%= user_path @conn, :index %>">Users</a></li>
                    <li><a href="<%= exhibition_user_path @conn, :index %>">Exhibition-Users</a></li>
                    <li><a href="<%= user_course_path @conn, :index %>">Users-Courses</a></li>
                </ul>
            </div>
            <div class="btn-group" id="dropdown2">
                <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu2"
                        data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="true">
                    API links
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
                  <li>
                  <%= link "user search", 
                  to: user_search_path(@conn, :index), 
                  class: "btn btn-primary btn" %>
                    </li>
                </ul>
                <%= if (! assigns[:current_user] ) && display_banner?(@conn) do %>
                  <%= link "Sign in", 
                    to: auth_path(@conn, :request, :identity), 
                    class: "btn btn-primary btn" %>
                  <%= link "Sign in (FB)", 
                    to: auth_path(@conn, :request, :facebook), 
                    class: "btn btn-primary btn" %>
                  <%= link "Sign in (Google)", 
                    to: auth_path(@conn, :request, :google), 
                    class: "btn btn-primary btn" %>
                <%= end %>
            </div>
            <div class="btn-group">
                <%= if assigns[:current_user] do %>
                <%= link "Logout",
                to: auth_path(@conn, :delete),
                method: :delete,
                class: "btn btn-primary btn" %>
                <%= end %>
            </div>
        </nav>
    </header>
    <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
    <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
    <main role="main">
        <%= render @view_module, @view_template, assigns %>
    </main>
    <div id="footer">
       Current locale : <%= current_locale(@conn) %> 
    </div>
</div> <!-- /container -->
<script src='<%= static_path(@conn, "/js/app.js") %>'></script>

</body>
</html>

web/templates/layout/frontend.html.eex
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello College!</title>
    <link rel="stylesheet" href='<%= static_path(@conn, "/css/app.css") %>'>
</head>

<body>
<div class="container">
    <header class="header">
    </header>
    <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
    <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
    <main role="main">
        <%= render @view_module, @view_template, assigns %>
    </main>
    <div id="footer">
       Current locale : <%= current_locale(@conn) %> 
    </div>
</div> <!-- /container -->
<script src='<%= static_path(@conn, "/js/app.js") %>'></script>

</body>
</html>